### ISSUE TITLE
bower installation ENOTFOUND

### ISSUE THREAD

**Issue by HOuaghad** [fmaturel/angular-weekly-scheduler#1]
When trying to install the package from bower, I get
```
$ bower                        ENOTFOUND Package angular-weekly-scheduler not found
```

**Comment by fmaturel** [comment]
Hi ! 
Are you missing the "r" at the end of "angular-weekly-scheduler"?

**Comment by HOuaghad** [comment]
No, I apologize for making such typo in the issue but no.

**Comment by fmaturel** [comment]
OK, I certainly forgot to publish the latest version in bower registry. I'll be able to correct that next week. Can you use npm "npm install" command instead in the meantime ?

**Comment by HOuaghad** [comment]
Thank you, I'll just would like you to not close this until you publish it, as to add it to my bower.json file as for production we miss on nothing.

PS: Where can I find `weeklySchedulerI18N`

**Comment by fmaturel** [comment]
I won't close the issue until it is resolved. 'weeklySchedulerI18N' is packaged in the distribution js file in 'dist'. Just add it to the list of angular modules you use and it should be fine.

**Comment by fmaturel** [comment]
I've registered the package with command `bower register angular-weekly-scheduler git://github.com/fmaturel/angular-weekly-scheduler`.
This should make it available to bower.

**Comment by HOuaghad** [comment]
All cool now! Thank you

![screenshot from 2016-08-22 10-00-24](https://cloud.githubusercontent.com/assets/13497307/17849139/4d83b9f8-684f-11e6-822e-64d850ccf750.png)
