### ISSUE TITLE
$scope.model data 

### ISSUE THREAD

**Issue by foudreclair** [fmaturel/angular-weekly-scheduler#10]
Hello, 
I'm new in development with AngularJS. Your module it's great. I have try to use it with a SQL database. But I not understand how I can generate a $scope.model with my SQL data. 
I have two tables :
-Plan :  the label of plan 
-Périodes : Start, end, id plan 
I have see with angular it's not possible to use For in $scope.model
Actually I use a factory for get with no resource the data SQL and push it in $scope.model.
Have you the solution for use my SQL data? 

Thanks a lot for your help. 

Ps: sorry for my English.

**Comment by fmaturel** [comment]
Hi, thanks for using the angular-weekly-scheduler.
Please provide more details on your software architecture:

- Where is your SQL service? on a server, or on the browser (WebSQL) ?

**Comment by foudreclair** [comment]
It's a MYSQL server. I use Spring (backend) with AngularJS (frontend).

**Comment by fmaturel** [comment]
Then your frontend (angular) should query the backend and receive your tables content as json.
This json can then be used to populate the $scope model.

**Comment by foudreclair** [comment]
Yes that's it. But i not understand how i can push the data in the good format for $scope.model.
I can't use For in $scope.model
How the $scope.model will know how many periods in an item?
He exist a solution for create a loop in scope model ? 
Thanks a lot for your answers

**Comment by foudreclair** [comment]
i have try this but he doesn't work.
data = the result of my queries SQL 
function print(data) {
    for(var i = 0;CONDITION;i++) {
       $scope.model = {
        options: {/*monoSchedule: true*/}, 
         label: data[i].label,
         schedules: [
         for(var j = 0;CONDITION...;j++) {
                 {start: moment(data[j].start).toDate(), end: moment(data[j].end).toDate()},
         }
         ]
        },
    }
}

I hope you understand my problem.

**Comment by foudreclair** [comment]
I succeeded to push my SQL data on your module. I have a function in service for push in array my SQL data. 
Thanks for your help. 

But I have an a question I want to increase the size of one month where I can modify that?

**Comment by fmaturel** [comment]
You can have a look at [angular-weekly-scheduler/app/ng-weekly-scheduler/js/directives/weekly-scheduler.js](https://github.com/fmaturel/angular-weekly-scheduler/blob/master/app/ng-weekly-scheduler/js/directives/weekly-scheduler.js#L92)

````
// Then resize schedule area knowing the number of weeks in scope
el.firstChild.style.width = schedulerCtrl.config.nbWeeks / 53 * 200 + '%';
````

The `200` means that the scheduler's width is 200% the container's div width.
If you change it to `300`, this will increase your month's width.

**Comment by foudreclair** [comment]
You use a cache for your application? 
Because when I edit this no visible changes. 
I have restart my web server but this doesn't work.

**Comment by fmaturel** [comment]
Depends if you use the source code or the compiled code.
If you included the script in the `dist` directory, then the code to change is in [dist/js/ng-weekly-scheduler.js](https://github.com/fmaturel/angular-weekly-scheduler/blob/master/dist/js/ng-weekly-scheduler.js#L349)

**Comment by foudreclair** [comment]
Ok thanks for your answers.
I search :)
