### ISSUE TITLE
Asp.net core 2.0

### ISSUE THREAD

**Issue by Nagendhran1988** [fmaturel/angular-weekly-scheduler#14]
Hi  fmatural,

How to run this project  in Asp.net core 2.0?What are dependenices  file need or not  to run this project in asp.net core 2.0 ?pls advise

**Comment by fmaturel** [comment]
This library is a front-end angular module, that should interact with a Rest / Json API server.

- Server side, you should have your API written in ASP.net for your scheduled task:
- Front side (meaning on the client browser), you should have an HTML page with some JavaScript calling angularjs and angular-weekly-scheduler module. You would write the core methods that retrieve the schedules from the server as Json, and use that Json on the angular-weekly-scheduler to display, for instance, current user's schedules.

You could have a look at [how to create a web api in asp.net](https://docs.microsoft.com/en-us/aspnet/web-api/overview/older-versions/build-restful-apis-with-aspnet-web-api), and use the punker in this project readme to have a first implementation of your project.
