### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by suyalcinkaya** [fmaturel/angular-weekly-scheduler#7]
First of all thank you for the directive, it looks really nice. I wish there was a documentation for it. Therefore I got some questions..

1. Can I set min and max dates for the start and end dates of schedules?

2. Can I block the "Add New" property when mouse hovering on scheduler? (do not want to use it)

3.  Can I block(hide) "Delete" button? (do not want to use it)

**Comment by fmaturel** [comment]
Hi!
Thanks for using this library, actually I'd like to have some time to create a proper documentation, but for the time being it's really impossible. Hope those hints will be sufficient : 

1. No you can't, but you could fork and adapt the library to do it.
I should be rather simple to add an optional field in configuration that would override calculated configuration in [weekly-scheduler.js](https://github.com/fmaturel/angular-weekly-scheduler/blob/a95b203c9b29d8bc3b64c22039d4174c4c8f4a5f/app/ng-weekly-scheduler/js/directives/weekly-scheduler.js) line 17

2. and 3., I would use CSS `display: none;` to hide elements you dont wan't to be displayed.
Respectively
```
multi-slider weekly-slot:hover .remove {
  display: none;
}
```
and
```
multi-slider:hover .ghost {
  display: none;
}
```
Happy hacking :yum:

**Comment by suyalcinkaya** [comment]
Thanks for the quick reply. Solved 2. and 3. I'll look the 1. when I complete my deals asap. Got two more question. 

4. I guess directive accepts the longest item's start date as a start date(Months section). But the end date doesn't work like that. Can I set it as in the start date?

5. Can I just block the start and end dates modifying? Only movements? Just asking.

**Comment by fmaturel** [comment]
Hi, sorry for the late answer, I run out of time on maintaining this.
Still need some help on that?
