### ISSUE TITLE
Year 2016 has 53 weeks

### ISSUE THREAD

**Issue by Bartaf83** [fmaturel/angular-weekly-scheduler#8]
As in the demo the year 2016 contains 53 weeks.
I checked the number of weeks in 2016 , it's supposed to be 52 as shown in [here ](http://www.epochconverter.com/weeks/2016) and [here ](http://week-number.net/calendar-with-week-numbers-2016.html)too.
i think it's moment.js's mistake but is it possible to fix it ?

**Comment by fmaturel** [comment]
Hi,
You're right, week number of a year depends on the locale settings of the scheduler.
On the [demo site](http://www.dijit.fr/demo/angular-weekly-scheduler/), it seems that week 1 of 2016 starts at end of 2015 where it should start January 4, 2016.

I checked [momentjs week method](https://momentjs.com/docs/#/get-set/iso-week/), and it seems I should rather use the isoWeek method to be compliant with ISO.
```
var moment = require('moment');

// Using week (as in scheduler)
console.log(moment('20160104').week()); // => 2

// Using isoWeek (should be used)
console.log(moment('20160103').isoWeek()); // => 53
console.log(moment('20160104').isoWeek()); // => 1
```

I have to evaluate the impact of what written in the doc `When setting the week of the year, the day of the week is retained.`
If you have some time to look at this, any PR is welcomed.
Thanks for pointing this out.

**Comment by Bartaf83** [comment]
Thanks for your replay, i'm trying to figure out the whole code and i'd like to contribute to this project later. I wasn't active in github and i would know where i can ask code-related questions. I have been reading this [guide](https://guides.github.com/activities/contributing-to-open-source/) and this [issue](http://stackoverflow.com/questions/23482670/github-in-code-questions-in-a-pull-request)

**Comment by fmaturel** [comment]
Summary of the steps to PR:
* You've to fork the project in your repositories, 
* clone your fork locally.
* commit the correction to your remote fork
* ask to PR to my github repository.

@see the `Pull Request Pro Tips` of the guide you mentioned.
